SELECT A.PRODUCT_ID, A.PRODUCT_NAME, (A.PRICE * B.SUM_AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A
JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT
    FROM FOOD_ORDER 
    WHERE PRODUCE_DATE BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD') 
                      AND TO_DATE('2022-05-31', 'YYYY-MM-DD') + 0.99999
    GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID	= B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;