SELECT F.CATEGORY, A.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) A ON F.CATEGORY = A.CATEGORY AND F.PRICE = A.MAX_PRICE
ORDER BY A.MAX_PRICE DESC;